# Generated by Django 4.2.7 on 2025-11-22 11:22

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("regular", "普通用户"),
                            ("admin", "管理员"),
                            ("superuser", "超级管理员"),
                        ],
                        default="regular",
                        max_length=20,
                        verbose_name="用户类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("inactive", "非活跃"),
                            ("suspended", "暂停"),
                            ("deleted", "已删除"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="用户状态",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        help_text="用户昵称，可用于显示",
                        max_length=50,
                        verbose_name="昵称",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="用户头像图片",
                        null=True,
                        upload_to="avatars/%Y/%m/",
                        verbose_name="头像",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="用户手机号码，用于登录和通知",
                        max_length=11,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="请输入有效的手机号码", regex="^1[3-9]\\d{9}$"
                            )
                        ],
                        verbose_name="手机号码",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="用户生日", null=True, verbose_name="生日"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="用户个人简介，最多500字",
                        max_length=500,
                        verbose_name="个人简介",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Shanghai",
                        help_text="用户所在时区",
                        max_length=50,
                        verbose_name="时区",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="zh-hans",
                        help_text="用户偏好语言",
                        max_length=10,
                        verbose_name="语言",
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False,
                        help_text="用户邮箱是否已通过验证",
                        verbose_name="邮箱已验证",
                    ),
                ),
                (
                    "phone_verified",
                    models.BooleanField(
                        default=False,
                        help_text="用户手机是否已通过验证",
                        verbose_name="手机已验证",
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="用户最后登录的IP地址",
                        null=True,
                        verbose_name="最后登录IP",
                    ),
                ),
                (
                    "registration_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="用户注册时的IP地址",
                        null=True,
                        verbose_name="注册IP",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="用户相关的额外元数据信息",
                        verbose_name="元数据",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="软删除标记，标记为删除的用户不会真正删除",
                        verbose_name="已删除",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="用户被软删除的时间",
                        null=True,
                        verbose_name="删除时间",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="用户创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="用户信息最后更新时间",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "users",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "男"),
                            ("F", "女"),
                            ("O", "其他"),
                            ("N", "不愿透露"),
                        ],
                        help_text="用户性别",
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        help_text="用户职业",
                        max_length=100,
                        verbose_name="职业",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        help_text="用户所在公司",
                        max_length=200,
                        verbose_name="公司",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="用户地址信息",
                        max_length=500,
                        verbose_name="地址",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="用户个人网站或博客",
                        verbose_name="个人网站",
                    ),
                ),
                (
                    "social_links",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="用户社交媒体链接，如微博、GitHub等",
                        verbose_name="社交媒体链接",
                    ),
                ),
                (
                    "interests",
                    models.TextField(
                        blank=True,
                        help_text="用户兴趣爱好",
                        max_length=1000,
                        verbose_name="兴趣爱好",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="用户个人标签，用于个性化推荐",
                        verbose_name="个人标签",
                    ),
                ),
                (
                    "privacy_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="用户隐私设置，控制信息公开程度",
                        verbose_name="隐私设置",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
                "db_table": "user_profiles",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="users_usernam_baeb4b_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["phone_number"], name="users_phone_n_a3b1c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["status"], name="users_status_9ca66f_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["user_type"], name="users_user_ty_578f8f_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="users_created_6541e9_idx"),
        ),
    ]
